Vagrant.configure('2') do |config|
  config.vm.box = 'yarsiemanym/ubuntu_18.04.1_desktop_amd64'
  config.vm.network 'private_network', ip: '192.168.34.11'
  config.vm.network 'forwarded_port', guest: 22, host: 2222, id: 'ssh', auto_correct: true

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.memory = '8192'
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--vram', '64']
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
    vb.name = 'Nar Shaddaa'
  end

  config.vm.provision 'shell', path: 'shell/install.sh'
end
